export const NEW_MESSAGE_REQUEST = "NEW_MESSAGE_REQUEST";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS";
export const NEW_MESSAGE_FAILURE = "NEW_MESSAGE_FAILURE";
export const NEW_MESSAGE_RESET = "NEW_MESSAGE_RESET";
