export const NEW_SUBSCRIPTION_REQUEST = "NEW_SUBSCRIPTION_REQUEST";
export const NEW_SUBSCRIPTION_SUCCESS = "NEW_SUBSCRIPTION_SUCCESS";
export const NEW_SUBSCRIPTION_FAILURE = "NEW_SUBSCRIPTION_FAILURE";
export const NEW_SUBSCRIPTION_RESET = "NEW_SUBSCRIPTION_RESET";
